efiSystemPartition: "/boot"
efiSystemPartitionSize: 1024M
userSwapChoices:
  - none
  - file
drawNestedPartitions: false
alwaysShowPartitionLabels: true
defaultFileSystemType: "btrfs"
availableFileSystemTypes: [ "btrfs", "ext4" ]
initialPartitionAttributes: []
btrfsSubvolumes:
  - { subvolume: "/",          mountPoint: "@" }
  - { subvolume: "/home",      mountPoint: "@home" }
  - { subvolume: "/var/log",   mountPoint: "@log" }
  - { subvolume: "/var/cache/pacman/pkg", mountPoint: "@pkg" }
  - { subvolume: "/.snapshots", mountPoint: "@snapshots" }
