units:
  - name: NetworkManager.service
    action: enable
  - name: sddm.service
    action: enable
  - name: systemd-timesyncd.service
    action: enable
  - name: firewalld.service
    action: enable
  - name: snapper-timeline.timer
    action: enable
  - name: snapper-cleanup.timer
    action: enable
