# Copy the live filesystem onto the target.
# archiso mounts the live root's source image at /run/archiso/airootfs.
unpack:
  - source: "/run/archiso/airootfs"
    sourcefs: "squashfs"
    destination: ""
