userShell: /usr/bin/fish   # bash (from `base`) remains as root's shell / fallback

defaultGroups:
  - wheel
  - network
  - video
  - audio
  - storage
  - input
autologinGroup: autologin
sudoersGroup: wheel
setRootPassword: true
doReusePassword: true
passwordRequirements:
  minLength: 1
