// Generated by scripts/generate-calamares-branding.py -- do not edit by hand.
// Design tokens from the AedwenOS System Surfaces design (palette_lib.py).
pragma Singleton
import QtQuick

QtObject {
    readonly property color surface: "#0d0b13"
    readonly property color scLow: "#12101b"
    readonly property color sc: "#181521"
    readonly property color scHigh: "#1f1c29"
    readonly property color scHighest: "#262331"
    readonly property color fg: "#e5e3ec"
    readonly property color fgVariant: "#bebbcd"
    readonly property color outline: "#878491"
    readonly property color outlineV: "#3e3b47"
    readonly property color primary: "#cdacff"
    readonly property color primaryFg: "#2d1c50"
    readonly property color pc: "#4b2888"
    readonly property color pcFg: "#eae2ff"
    readonly property color secC: "#37304e"
    readonly property color secCFg: "#dfdbed"
    readonly property color terC: "#701a37"
    readonly property color terCFg: "#ffdbe3"
    readonly property color errC: "#7f2021"
    readonly property color errCFg: "#ffd8d4"
    readonly property color err: "#ff9b93"
    // 8% on-surface state layer (hover)
    readonly property color state: Qt.rgba(229 / 255, 227 / 255, 236 / 255, 0.08)

    readonly property int rWin: 16
    readonly property int rInner: 10
    readonly property int rPop: 32
    readonly property int rCard: 20
    readonly property int rTile: 20

    // Spring ease and duration for shape morphs
    readonly property var ease: [0.34, 1.45, 0.55, 1, 1, 1]
    readonly property int dur: 420

    readonly property string font: "Roboto"
    readonly property string mono: "Roboto Mono"
    property FontLoader symbolsLoader: FontLoader { source: "fonts/MaterialSymbolsRounded-subset.ttf" }
    readonly property string symbols: symbolsLoader.name

    readonly property var icons: ({
        "add": "\ue145",
        "arrow_back": "\ue5c4",
        "arrow_forward": "\ue5c8",
        "check": "\ue668",
        "check_circle": "\uf0be",
        "close": "\ue5cd",
        "edit": "\uf097",
        "error": "\uf8b6",
        "expand_more": "\ue5cf",
        "hard_drive": "\uf80e",
        "info": "\ue88e",
        "keyboard": "\ue312",
        "language": "\uea07",
        "location_on": "\uf1db",
        "lock": "\ue899",
        "my_location": "\ue55c",
        "palette": "\ue40a",
        "person": "\uf0d3",
        "public": "\ue80b",
        "radio_button_checked": "\ue837",
        "radio_button_unchecked": "\ue836",
        "restart_alt": "\uf053",
        "schedule": "\uefd6",
        "search": "\uef7a",
        "storefront": "\uea12",
        "terminal": "\ueb8e",
        "translate": "\ue8e2",
        "usb": "\ue1e0",
        "view_quilt": "\ue8f1",
        "visibility": "\ue8f4",
        "visibility_off": "\ue8f5",
        "warning": "\uf083"
    })
    function icon(name) { return icons[name] || "" }
}
