#!/usr/bin/env python3
"""
Generate the AedwenOS GTK3 + GTK4/libadwaita theme from the same palette
used by the KDE colour scheme (scripts/palette_lib.py), matching the
"GTK & libadwaita apps" section of the AedwenOS System Surfaces design:
same 48px header bar with a centred title and a monochrome circular close
button, same pill buttons / switches / boxed list rows as the Qt widgets,
same seed colour.

Usage:
    scripts/generate-gtk-theme.py [--out DIR]
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from palette_lib import DEFAULT_SEED, SEEDS, palette  # noqa: E402

R_WIN, R_INNER, R_CARD = "16px", "10px", "20px"  # expressive shapes


def define_colors(p):
    lines = [f"@define-color ae_{k.replace('-', '_')} {v};" for k, v in p.items()]
    return "\n".join(lines)


def gtk3_css(p, dark):
    return f"""/* AedwenOS GTK3 theme -- generated by scripts/generate-gtk-theme.py, do not edit by hand */
{define_colors(p)}

* {{
  outline-color: alpha(@ae_primary, 0.5);
}}

window, .background {{
  background-color: @ae_surface;
  color: @ae_on_s;
}}

headerbar {{
  min-height: 48px;
  background-color: @ae_sc;
  color: @ae_on_s;
  border: none;
  box-shadow: none;
  padding: 0 8px;
}}
headerbar .title {{
  font-weight: 600;
  font-size: 14px;
}}
headerbar button.titlebutton {{
  border-radius: 9999px;
  min-width: 32px;
  min-height: 32px;
  background-color: transparent;
  color: @ae_on_s;
}}
headerbar button.titlebutton.close {{
  background-color: @ae_sc_highest;
}}
headerbar button.titlebutton:hover {{
  background-color: alpha(@ae_on_s, 0.08);
}}

button {{
  border-radius: 9999px;
  padding: 6px 18px;
  border: none;
  background-color: @ae_sc_highest;
  color: @ae_on_s;
  transition: background-color 200ms ease;
}}
button:hover {{ background-color: alpha(@ae_on_s, 0.08); }}
button.suggested-action {{
  background-color: @ae_primary;
  color: @ae_on_primary;
  font-weight: 600;
}}
button.suggested-action:hover {{ background-color: alpha(@ae_primary, 0.9); }}
button.destructive-action {{
  background-color: @ae_err_c;
  color: @ae_on_err_c;
}}
button.flat {{
  background-color: transparent;
  color: @ae_primary;
}}
button.flat:hover {{ background-color: alpha(@ae_primary, 0.08); }}
button:disabled {{ opacity: 0.45; }}

entry {{
  border-radius: {R_INNER};
  border: 1px solid @ae_outline;
  background-color: transparent;
  color: @ae_on_s;
  padding: 8px 12px;
}}
entry:focus {{
  border: 2px solid @ae_primary;
  padding: 7px 11px;
}}
entry.error {{ border-color: @ae_err; }}

checkbutton check, radiobutton radio {{
  border-radius: 4px;
  border: 2px solid @ae_on_sv;
  background-color: transparent;
  min-width: 18px;
  min-height: 18px;
}}
radiobutton radio {{ border-radius: 9999px; }}
checkbutton check:checked, radiobutton radio:checked {{
  background-color: @ae_primary;
  border-color: @ae_primary;
  color: @ae_on_primary;
}}

switch {{
  border-radius: 9999px;
  background-color: @ae_sc_highest;
  border: 2px solid @ae_outline;
  min-width: 44px;
  min-height: 26px;
}}
switch:checked {{
  background-color: @ae_primary;
  border-color: @ae_primary;
}}
switch slider {{
  border-radius: 9999px;
  background-color: @ae_outline;
  min-width: 18px;
  min-height: 18px;
}}
switch:checked slider {{ background-color: @ae_on_primary; }}

list, treeview {{
  background-color: @ae_surface;
  color: @ae_on_s;
}}
row {{ border-radius: {R_INNER}; }}
row:selected {{
  background-color: @ae_sec_c;
  color: @ae_on_sec_c;
}}
row:hover {{ background-color: alpha(@ae_on_s, 0.06); }}

notebook > header {{
  background-color: transparent;
  border-bottom: 1px solid @ae_outline_v;
}}
notebook > header tab {{
  color: @ae_on_sv;
  padding: 10px 16px;
}}
notebook > header tab:checked {{
  color: @ae_primary;
  font-weight: 600;
  box-shadow: inset 0 -3px 0 0 @ae_primary;
}}

popover {{
  border-radius: {R_CARD};
  background-color: @ae_sc_high;
  color: @ae_on_s;
  box-shadow: 0 8px 24px alpha(#000000, 0.35);
}}
menuitem {{ border-radius: {R_INNER}; }}
menuitem:hover {{ background-color: alpha(@ae_on_s, 0.08); }}

tooltip {{
  border-radius: 8px;
  background-color: @ae_on_s;
  color: @ae_surface;
}}

progressbar > trough {{
  border-radius: 3px;
  background-color: @ae_sec_c;
  min-height: 6px;
}}
progressbar > trough > progress {{
  border-radius: 3px;
  background-color: @ae_primary;
}}

scrollbar slider {{
  border-radius: 9999px;
  background-color: @ae_outline;
  min-width: 5px;
  min-height: 5px;
}}
scrollbar slider:hover {{ background-color: @ae_primary; }}
"""


def gtk4_css(p, dark):
    # GTK4 + libadwaita apps mostly pick up accent/colour-scheme from the
    # xdg-desktop-portal-kde portal (see kdeglobals AccentColor); this
    # stylesheet is a fallback for GTK4 apps that load a named theme
    # directly rather than going through libadwaita's StyleManager.
    return gtk3_css(p, dark).replace(
        "/* AedwenOS GTK3 theme -- generated by scripts/generate-gtk-theme.py, do not edit by hand */",
        "/* AedwenOS GTK4 theme -- generated by scripts/generate-gtk-theme.py, do not edit by hand */\n"
        "/* libadwaita apps: colours normally come from the portal (see /etc/xdg/kdeglobals AccentColor). */",
    )


def write_variant(out_root, seed, dark, expressive):
    H = SEEDS[seed]
    p = palette(H, dark, expressive)
    theme_name = f"AedwenOS-{seed.capitalize()}-{'Dark' if dark else 'Light'}"

    for gtk_dir, css in (
        ("gtk-3.0", gtk3_css(p, dark)),
        ("gtk-4.0", gtk4_css(p, dark)),
    ):
        d = os.path.join(out_root, theme_name, gtk_dir)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "gtk.css"), "w") as f:
            f.write(css)
        # gtk-dark.css is what GTK4 loads when prefer-dark-theme is set
        with open(os.path.join(d, "gtk-dark.css"), "w") as f:
            f.write(css)

    idx = os.path.join(out_root, theme_name, "index.theme")
    with open(idx, "w") as f:
        f.write(f"""[Desktop Entry]
Type=X-GNOME-Metatheme
Name={theme_name}
Comment=AedwenOS · {seed.capitalize()} ({"Dark" if dark else "Light"}), generated from the system seed colour

[X-GNOME-Metatheme]
GtkTheme={theme_name}
MetacityTheme={theme_name}
IconTheme=breeze-dark
CursorTheme=Aedwen
ButtonLayout=close:
""")
    return theme_name


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="iso/airootfs/usr/share/themes")
    ap.add_argument("--seed", default=None)
    args = ap.parse_args()

    seeds = [args.seed] if args.seed else SEEDS.keys()
    written = []
    for seed in seeds:
        for dark in (True, False):
            written.append(write_variant(args.out, seed, dark, expressive=True))

    print(f"Wrote {len(written)} GTK theme variants to {args.out}")
    print("Default: AedwenOS-" + DEFAULT_SEED.capitalize() + "-Dark")


if __name__ == "__main__":
    main()
