#!/usr/bin/env python3
"""
Generate the design-token files for the AedwenOS Calamares branding
(iso/airootfs/etc/calamares/branding/aedwenos/), from the same palette as
every other AedwenOS theme generator (palette_lib.py):

  - Theme.qml          QML singleton: colours, radii, motion, fonts and the
                       icon-name -> codepoint table used by every QML page
  - stylesheet.qss     Qt-widget styling for the pages that are not QML
                       (the Disk/partition step), per "App widgets" in the
                       AedwenOS System Surfaces design
  - branding.desc      only the `style:` block (sidebar colours) is rewritten
  - eagle-<colour>.png  the logo pre-tinted in the palette colours EagleMark
                       uses (a pre-rendered tint works on every Qt Quick
                       backend; a MultiEffect mask needs shader support)
  - fonts/MaterialSymbolsRounded-subset.ttf + LICENSE
                       Material Symbols Rounded (Apache-2.0), subset to the
                       icons in ICONS so the branding stays small. The
                       variable axes (FILL, wght, ...) are kept.

The full font and its codepoint table are downloaded from
github.com/google/material-design-icons unless --symbols-font/--codepoints
point at local copies.

Usage:
    scripts/generate-calamares-branding.py [--seed violet] [--light] [--baseline]

Requires fonttools and python-cairo.
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile
import urllib.request

import cairo

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from palette_lib import DEFAULT_SEED, SEEDS, palette  # noqa: E402

BRANDING = "iso/airootfs/etc/calamares/branding/aedwenos"
FONT_URL = ("https://github.com/google/material-design-icons/raw/master/variablefont/"
            "MaterialSymbolsRounded%5BFILL,GRAD,opsz,wght%5D")
LICENSE_URL = "https://raw.githubusercontent.com/google/material-design-icons/master/LICENSE"

# Every Material Symbols glyph the installer QML refers to (Theme.icon("name")).
ICONS = [
    "add", "arrow_back", "arrow_forward", "check", "check_circle", "close", "edit",
    "error", "expand_more", "hard_drive", "info", "keyboard", "language", "location_on",
    "lock", "my_location", "palette", "person", "public", "radio_button_checked",
    "radio_button_unchecked", "restart_alt", "schedule", "search", "storefront",
    "terminal", "translate", "usb", "view_quilt", "visibility", "visibility_off", "warning",
]

# Palette colours the eagle is drawn in: EagleMark `tint` -> palette key.
EAGLE_TINTS = {"primary": "primary", "primary-fg": "on-primary", "pc-fg": "on-pc"}

# Shapes from the design's `SHAPES` table.
SHAPES = {
    "baseline": {"r-win": 12, "r-inner": 8, "r-pop": 28, "r-card": 16, "r-tile": 16,
                 "ease": [0.2, 0, 0, 1], "dur": 300},
    "expressive": {"r-win": 16, "r-inner": 10, "r-pop": 32, "r-card": 20, "r-tile": 20,
                   "ease": [0.34, 1.45, 0.55, 1], "dur": 420},
}


def camel(key):
    """QML property name for a palette key. "on-x" (content colour on x)
    becomes "xFg" -- QML reads names like onPrimary as signal handlers."""
    if key == "on-s":
        return "fg"
    if key == "on-sv":
        return "fgVariant"
    fg = key.startswith("on-")
    head, *rest = (key[3:] if fg else key).split("-")
    name = head + "".join(part.capitalize() for part in rest)
    return name + "Fg" if fg else name


def rgba(hex_color, alpha):
    h = hex_color.lstrip("#")
    r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
    return f"rgba({r}, {g}, {b}, {alpha})"


def load_codepoints(path):
    table = {}
    with open(path) as f:
        for line in f:
            name, cp = line.split()
            table[name] = int(cp, 16)
    missing = [n for n in ICONS if n not in table]
    if missing:
        sys.exit(f"icons missing from {path}: {', '.join(missing)}")
    return {n: table[n] for n in ICONS}


def theme_qml(p, shape, codepoints):
    colours = "\n".join(
        f'    readonly property color {camel(k)}: "{v}"' for k, v in p.items()
    )
    icons = ",\n".join(f'        "{n}": "\\u{cp:04x}"' for n, cp in codepoints.items())
    e = shape["ease"]
    return f"""// Generated by scripts/generate-calamares-branding.py -- do not edit by hand.
// Design tokens from the AedwenOS System Surfaces design (palette_lib.py).
pragma Singleton
import QtQuick

QtObject {{
{colours}
    // 8% on-surface state layer (hover)
    readonly property color state: Qt.rgba({int(p["on-s"][1:3], 16)} / 255, {int(p["on-s"][3:5], 16)} / 255, {int(p["on-s"][5:7], 16)} / 255, 0.08)

    readonly property int rWin: {shape["r-win"]}
    readonly property int rInner: {shape["r-inner"]}
    readonly property int rPop: {shape["r-pop"]}
    readonly property int rCard: {shape["r-card"]}
    readonly property int rTile: {shape["r-tile"]}

    // Spring ease and duration for shape morphs
    readonly property var ease: [{e[0]}, {e[1]}, {e[2]}, {e[3]}, 1, 1]
    readonly property int dur: {shape["dur"]}

    readonly property string font: "Roboto"
    readonly property string mono: "Roboto Mono"
    property FontLoader symbolsLoader: FontLoader {{ source: "fonts/MaterialSymbolsRounded-subset.ttf" }}
    readonly property string symbols: symbolsLoader.name

    readonly property var icons: ({{
{icons}
    }})
    function icon(name) {{ return icons[name] || "" }}
}}
"""


def stylesheet(p, shape):
    ri = shape["r-inner"]
    return f"""/* Generated by scripts/generate-calamares-branding.py -- do not edit by hand.
 * Qt-widget pages (Disk step), styled per "App widgets" in the AedwenOS
 * System Surfaces design: 36px pill buttons, outlined fields, 8% state layer. */

QWidget {{
    font-family: "Roboto";
}}

QPushButton {{
    min-height: 36px;
    padding: 0 18px;
    border: none;
    border-radius: 18px;
    background-color: {p["sec-c"]};
    color: {p["on-sec-c"]};
    font-weight: 600;
}}
QPushButton:hover {{ background-color: {p["sc-highest"]}; }}
QPushButton:default {{
    background-color: {p["primary"]};
    color: {p["on-primary"]};
}}
QPushButton:disabled {{
    background-color: {rgba(p["on-s"], 0.12)};
    color: {rgba(p["on-s"], 0.45)};
}}
QToolButton {{
    min-height: 32px;
    min-width: 32px;
    border: none;
    border-radius: 16px;
    background: transparent;
    color: {p["on-s"]};
}}
QToolButton:hover {{ background-color: {rgba(p["on-s"], 0.08)}; }}

QLineEdit, QComboBox, QSpinBox {{
    min-height: 36px;
    padding: 0 12px;
    border: 1px solid {p["outline"]};
    border-radius: {ri}px;
    background: transparent;
    color: {p["on-s"]};
    selection-background-color: {p["primary"]};
    selection-color: {p["on-primary"]};
}}
QLineEdit:focus, QComboBox:focus, QSpinBox:focus {{
    border: 2px solid {p["primary"]};
    padding: 0 11px;
}}
QComboBox::drop-down {{ border: none; width: 28px; }}
QComboBox QAbstractItemView {{
    padding: 4px;
    border: none;
    border-radius: 16px;
    background-color: {p["sc-high"]};
    color: {p["on-s"]};
    selection-background-color: {p["sec-c"]};
    selection-color: {p["on-sec-c"]};
    outline: 0;
}}

QTreeView, QListView, QTableView {{
    border: 1px solid {p["outline-v"]};
    border-radius: {ri}px;
    background-color: {p["sc-low"]};
    alternate-background-color: {p["sc-low"]};
    selection-background-color: {p["sec-c"]};
    selection-color: {p["on-sec-c"]};
    outline: 0;
}}
QHeaderView::section {{
    padding: 6px 8px;
    border: none;
    border-bottom: 1px solid {p["outline-v"]};
    background: transparent;
    color: {p["on-sv"]};
    font-weight: 600;
}}

QScrollBar:vertical {{ width: 10px; background: transparent; margin: 2px; }}
QScrollBar:horizontal {{ height: 10px; background: transparent; margin: 2px; }}
QScrollBar::handle {{ background: {p["outline"]}; border-radius: 3px; min-height: 24px; min-width: 24px; }}
QScrollBar::add-line, QScrollBar::sub-line, QScrollBar::add-page, QScrollBar::sub-page {{
    background: none; border: none; width: 0; height: 0;
}}

QToolTip {{
    padding: 6px 10px;
    border: none;
    border-radius: 8px;
    background-color: {p["on-s"]};
    color: {p["surface"]};
}}

QProgressBar {{
    min-height: 8px;
    max-height: 8px;
    border: none;
    border-radius: 4px;
    background-color: {p["sec-c"]};
    color: transparent;
}}
QProgressBar::chunk {{ border-radius: 4px; background-color: {p["primary"]}; }}
"""


def write_style_block(path, p):
    block = (
        "style:\n"
        f'    SidebarBackground:        "{p["sc-low"]}"\n'
        f'    SidebarText:              "{p["on-sv"]}"\n'
        f'    SidebarTextCurrent:       "{p["on-sec-c"]}"\n'
        f'    SidebarBackgroundCurrent: "{p["sec-c"]}"\n'
    )
    with open(path) as f:
        src = f.read()
    new, n = re.subn(r"^style:\n(?:[ \t]+\S.*\n)*", block, src, flags=re.M)
    if n != 1:
        sys.exit(f"could not find a single `style:` block in {path}")
    with open(path, "w") as f:
        f.write(new)


def tinted_eagles(out, p, size=256):
    """logo.png (white eagle on transparency) as eagle-<tint>.png per tint."""
    logo = cairo.ImageSurface.create_from_png(os.path.join(out, "logo.png"))
    # Crop to the eagle itself: logo.png carries wide transparent margins.
    w, h_, stride = logo.get_width(), logo.get_height(), logo.get_stride()
    data = logo.get_data()
    rows = [y for y in range(h_) if any(data[y * stride + x * 4 + 3] for x in range(0, w, 2))]
    cols = [x for x in range(w) if any(data[y * stride + x * 4 + 3] for y in range(rows[0], rows[-1] + 1, 2))]
    x0, y0, bw, bh = cols[0], rows[0], cols[-1] - cols[0] + 1, rows[-1] - rows[0] + 1
    scale = size / max(bw, bh)
    for tint, key in EAGLE_TINTS.items():
        h = p[key].lstrip("#")
        rgb = [int(h[i : i + 2], 16) / 255 for i in (0, 2, 4)]
        surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, size, size)
        ctx = cairo.Context(surface)
        ctx.translate((size - bw * scale) / 2, (size - bh * scale) / 2)
        ctx.scale(scale, scale)
        ctx.set_source_rgb(*rgb)
        ctx.mask_surface(logo, -x0, -y0)
        surface.write_to_png(os.path.join(out, f"eagle-{tint}.png"))


def fetch(url, dest):
    print(f"downloading {url}")
    urllib.request.urlretrieve(url, dest)
    return dest


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=BRANDING)
    ap.add_argument("--seed", default=DEFAULT_SEED)
    ap.add_argument("--light", action="store_true")
    ap.add_argument("--baseline", action="store_true")
    ap.add_argument("--symbols-font", help="local MaterialSymbolsRounded[...].ttf")
    ap.add_argument("--codepoints", help="local MaterialSymbolsRounded[...].codepoints")
    args = ap.parse_args()

    p = palette(SEEDS[args.seed], dark=not args.light, expressive=not args.baseline)
    shape = SHAPES["baseline" if args.baseline else "expressive"]

    with tempfile.TemporaryDirectory() as tmp:
        font = args.symbols_font or fetch(FONT_URL + ".ttf", os.path.join(tmp, "msr.ttf"))
        cps = args.codepoints or fetch(FONT_URL + ".codepoints", os.path.join(tmp, "msr.codepoints"))
        codepoints = load_codepoints(cps)

        fonts_dir = os.path.join(args.out, "fonts")
        os.makedirs(fonts_dir, exist_ok=True)
        subset = os.path.join(fonts_dir, "MaterialSymbolsRounded-subset.ttf")
        subprocess.run(
            [sys.executable, "-m", "fontTools.subset", font,
             "--unicodes=" + ",".join(f"U+{cp:04X}" for cp in codepoints.values()),
             "--layout-features=*", "--no-hinting", "--output-file=" + subset],
            check=True,
        )
        fetch(LICENSE_URL, os.path.join(fonts_dir, "LICENSE"))

    with open(os.path.join(args.out, "Theme.qml"), "w") as f:
        f.write(theme_qml(p, shape, codepoints))
    with open(os.path.join(args.out, "stylesheet.qss"), "w") as f:
        f.write(stylesheet(p, shape))
    write_style_block(os.path.join(args.out, "branding.desc"), p)
    tinted_eagles(args.out, p)

    print(f"Wrote Theme.qml, stylesheet.qss, branding.desc style and icon font ({len(codepoints)} icons) to {args.out}")


if __name__ == "__main__":
    main()
